repos:
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-import-order',
            'flake8-quotes',
            'flake8-bugbear'
        ] 